# Generated by Django 3.2.8 on 2021-11-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('itunes_explicit', models.BooleanField()),
                ('itunes_category', models.CharField(max_length=20)),
                ('itunes_complete', models.BooleanField(default=False)),
                ('itunes_type', models.CharField(choices=[('ep', 'Episodic'), ('se', 'Serial')], default='ep', max_length=8)),
                ('spotify_limit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
